# @package _group_

generator:
  source: networks # TODO: rename into stylegan2?
  use_noise: true
  w_dim: 512
  c_dim: ${dataset.c_dim}
  input: {type: "const"}
  motion: {time_enc: {}}

discriminator:
  source: networks # TODO: rename into stylegan2?
  mbstd_group_size: 4

loss_kwargs:
  source: StyleGAN2Loss
  # r1_gamma: 10.0
  style_mixing_prob: 0.9
  pl_weight: 2.0
  motion_reg: {coef: 0.0}

optim:
  generator: {}
  discriminator: {}
