# @package _group_
path: /ibex/ai/home/shenx/video/data/${dataset.name}
path_for_slurm_job: ${env.datasets_dir}/${dataset.name}
name: rainbow_jelly_${dataset.resolution}
resolution: 256
fps: 30
motion_z_distance: 64
augpipe: easy
