# @package _group_

path: /ibex/ai/home/shenx/video/data/${dataset.name}
path_for_slurm_job: ${env.datasets_dir}/${dataset.name}
name: ucf101_${dataset.resolution}
resolution: 256
fps: 25
augpipe: easy